### ISSUE TITLE
Questions regarding depth values

### ISSUE THREAD

**Issue by lukaboljevic** [y-zheng18/point_odyssey#14]
Hello! I have two questions regarding the depth images/values.

Based to my understanding, the ground truth depth PNG images are 16-bit. Then, by dividing with 65535.0 and multiplying with 1000.0 (as in [this line](https://github.com/y-zheng18/point_odyssey/blob/main/utils/reprojection.py#L88)) the depth is converted to milimeters? Is this correct? I inferred this from the other two issues related to depth (#2, #6), but these lines then confuse me: 

https://github.com/y-zheng18/point_odyssey/blob/2e8cc2f75b78b966da279bc76ba171ff42b732ca/utils/reprojection.py#L47-L49

It states that you want to use max depth of 10 m(eters) for visualization. Can you clarify?

Secondly, what is the "unit" for the original depth values (from the 16-bit PNG image), i.e. what do the values represent? Obviously, depth, but in meters? Milimeters? Or something else?

Sorry if the questions are silly, it's my first time dealing with depth images so I wanted to understand what I'm looking at. Thanks in advance!

**Comment by y-zheng18** [comment]
Hi, the original depth is rendered as .tiff format in meters, and converted to png by using (depth_tiff * 65535 / 1000), supposing the max depth is 1000 meters. To convert png back to meter depth, you can use depth_png / 65535 * 1000.

**Comment by lukaboljevic** [comment]
Ah, so everything is in meters, I see. It makes more sense now. That answers both questions then. Thank you very much for the quick answer!
