### ISSUE TITLE
Question about trajs_3d in annotation file

### ISSUE THREAD

**Issue by yuantianyuan01** [y-zheng18/point_odyssey#19]
Thank you for providing this excellent dataset!

I have a few questions on the trajs_3d array in the annotation files. As I understand, trajs_3d has a shape of (S, N, 3), and I’d like to confirm some details:

1. Does the first axis (S) represent time steps, and the second axis (N) represent point indices?
2. Are the 3D coordinates provided in world coordinates, or are they in a different reference frame?
3. I noticed that the value of N is smaller than the total number of pixels (H*W). What's the criteria used for selecting these points as keypoints?

Thank you very much for your time and assistance!

**Comment by y-zheng18** [comment]
Hi, thanks for the questions.

1. yes
2. yes they are in world coordinates, you can try this: https://github.com/aharley/pips2/blob/master/datasets/pointodysseydataset_3d.py to load those data
3. We basically sample points on the 3D surface to get sparse point trajs.

**Comment by yuantianyuan01** [comment]
Thank you for the quick reply.
