### ISSUE TITLE
Infinite Depth Values in `animal2_s` Video for Smoke Regions

### ISSUE THREAD

**Issue by m43** [y-zheng18/point_odyssey#2]
Hello and thank you for the amazing dataset! I've been working with the validation set and observed that the `animal2_s` video contains regions with maximum depth values, specifically where there's an emission of smoke from the ground. I've included a GIF below for reference, where the RGB images are presented on the top and the corresponding depth maps on the bottom.

Given the nature of smoke and its challenges for RGBD sensors, I'm curious to understand if this is the expected representation in the dataset. Is the smoke intended to be portrayed with an "infinite" or maximum depth value in this scenario? I'd appreciate any insights or clarifications on this. Thanks!

![video.animal2_s.10fps](https://github.com/y-zheng18/point_odyssey/assets/17498813/381c4ffb-0762-427c-9eb5-4c755d163a99)

**Comment by y-zheng18** [comment]
While we do want to render the actual depth of the smokes, it seems this can't be done by the Blender engine. In fact, the z depth of the volumetric shader is not directly passed during rendering. You might need to add more complex 
nodes to pass the z value in blender, if you want to have depth of smoke regions.

Those smokes are added to increase occlusions of our scenes to make the tracking more challenging. So in addition to using depth for generating tracking annotations, we also incorporate masks, to determine whether the point is blocked, which could solve the invalid depth problem of smoke.

**Comment by m43** [comment]
Thank you for the clarification! I'll be closing this issue as my primary concern has been answered. However, I'd remain grateful for any future insights or updates regarding this topic.

Separately, I wanted to clarify the depth values. Based on my understanding, the depth values from Blender's depth-pass are [rescaled to the `[0, 65535]` range based on each video's min-max depth range](https://github.com/y-zheng18/point_odyssey/blob/d135b5267717a83e3529edf7f75286994f6ba3da/utils/file_io.py#L300-L305) and stored as `.png` files. This implies that we cannot retrieve the actual depth in world or camera space from the post-processed png files as we do not know the initial per-video min-max depth range. Additionally, it seems that the [tiff files with the raw depth](https://github.com/y-zheng18/point_odyssey/blob/d135b5267717a83e3529edf7f75286994f6ba3da/utils/file_io.py#L298) aren't publicly available. Could you please confirm? Thanks again!

**Comment by y-zheng18** [comment]
The original tiff files are too large, so we convert them to png images. In this way, depth is saved in millimeters and restored as (depth_map * 65535 / 1000). The max and min of the actual depth are set as 1000 and 0, and we replace the depth larger than the max value with 1000.

**Comment by DQiaole** [comment]
> The original tiff files are too large, so we convert them to png images. In this way, depth is saved in millimeters and restored as (depth_map * 65535 / 1000). The max and min of the actual depth are set as 1000 and 0, and we replace the depth larger than the max value with 1000.

Hello, sorry to bother. According to the folowing codes, I find the depth larger than the max value is replaced with **0**. Besides, the max of the depth is from **max = np.max(data)**, which I think may not necessarily be DEPTH_MAX. Could you please confirm? Thanks!
https://github.com/y-zheng18/point_odyssey/blob/d135b5267717a83e3529edf7f75286994f6ba3da/utils/file_io.py#L294-L305

**Comment by y-zheng18** [comment]
Yes, but this code is only for visualization purpose. In the released dataset, the png files are converted as described above. And as you can see in the gif above, the invalid value is replaced by the max value (65535) there, and the depth is consistent throughout the video.

**Comment by DQiaole** [comment]
Thanks!

**Comment by m43** [comment]
Thanks! Do you plan to release the codebase that generated the released dataset? It might be useful for debugging and digging out details such as how the depth was computed or other post-processing details
