### ISSUE TITLE
Motion Retargeting

### ISSUE THREAD

**Issue by rwn17** [y-zheng18/point_odyssey#3]
Hi @y-zheng18 , thanks for your excellent work! I'm trying to generate some sequences for my research with point_odyssey. But I come across some issues when retargeting the motion. 

The retargeted motion looks like following figures. The retargeted motion is barely smpl-x model without any texture. 
![Screenshot from 2023-08-10 16-03-36](https://github.com/y-zheng18/point_odyssey/assets/54616858/c3f7eb06-d307-4db3-bf12-129fb29444d2)

When transferring the fhe fbx module to Blender. I didn't rename the armature but changed the code as flowing:
```[python]
        for i, character in enumerate(character_list):
            character_collection_path = os.path.join(self.character_path, character, 'Collection')
            bpy.ops.wm.append(directory=character_collection_path, filename='Armature')
            skeleton = bpy.data.objects['Armature']

            self.retarget_smplx2skeleton(skeleton, motion_list[i])
```

I'm not very familiar with Blender, so I would be extremely grateful if you could provide any suggestions. Thank you in advance.

Bests,
Weining

**Comment by rwn17** [comment]
I just play with it a little bit more. It works well with one person but collapses after the 2nd person adding in.

One person:
![image](https://github.com/y-zheng18/point_odyssey/assets/54616858/af37a483-f687-4470-a634-693e9b452c2d)

Two person:
![image](https://github.com/y-zheng18/point_odyssey/assets/54616858/7c71e61c-4c46-4e19-8580-07fab2e0f2c2)

**Comment by y-zheng18** [comment]
ok I see. The character is firstly retargeted by one motion and then by another, which is probably problematic. Since you have two motions, the code expects you to have two human models, and that's why you need to rename the armature and the collections to specify which character to be retargeted. Simply double-click and change the name in blender. Or you could also use the one-character version in your above case if it works fine.

**Comment by rwn17** [comment]
Thanks. Directly double-clicking and changing the name in blender is not perfectly compatible with the code but I fix it. I'm not sure whether it's related to the version of Blender or the character model I download. Thanks for your prompt response and I will close this issue.
