### ISSUE TITLE
Depth Values for Ground in Outdoor Scenes

### ISSUE THREAD

**Issue by m43** [y-zheng18/point_odyssey#6]
Hi, and thanks again for the dataset! I've noticed that the depth values for the ground seem to be noticeably higher than the depth values for the objects lying on the ground. This is only true for outdoor scenes. Do you know why this is the case and if it is expected?

Below are two scenes from the dataset, one is the `animal2_s` outdoor scene. The objects on the ground seem to be flying on the ground. The other scene is the `dancingroom3_3rd` indoor scene where the depth changes smoothly when objects touch the ground. The depths are visualized on a log scale for both scenes.

https://github.com/y-zheng18/point_odyssey/assets/17498813/0a01284b-851f-4d5d-bfe0-53c9ed46b0e8

https://github.com/y-zheng18/point_odyssey/assets/17498813/71852883-0963-418a-938e-49613e464247

**Comment by m43** [comment]
Also, the depth value range differs for indoor and outdoor scenes. Is there a best way you'd suggest I normalize or postprocess the depths? For example, the range of depth values for trajectories after rescaling by `1000/65535`  to get millimeters is about `[8mm, 73mm]` in the `animal2_s` outdoor scene, and `[2mm, 10mm]` in the `dancingroom3_3rd` indoor scene.

**Comment by y-zheng18** [comment]
Yes, as you have noticed, the ground depth in the outdoor scenes is not correct. We've fixed that and will update the dataset very soon.

For the depth values, outdoor scenes are 10 times larger than indoor scenes. We'll also update the depth values to make them more consistent.

**Comment by m43** [comment]
Thanks a lot!
