### ISSUE TITLE
Rokoko Studio Live Plugin Can not Find

### ISSUE THREAD

**Issue by urbaneman** [y-zheng18/point_odyssey#8]
Hi, thanks for your nice work.

I try install this repo, but I couldn't download this addon

> [Rokoko Studio Live Plugin for Blender](https://www.rokoko.com/en/products/studio-live-link) (for motion retargeting)

Could you download this addon in google cloud or other cloud, and tell me the new link? Thanks.

btw, I use Linux.

**Comment by y-zheng18** [comment]
Thanks for the information! Now it moves to [https://www.rokoko.com/integrations/blender](https://www.rokoko.com/integrations/blender).
